baseURL = 'https://www.vange.jewelry/'
languageCode = 'en-us'
title = 'vangeJewelry'

theme = 'Au'

# --- PAGINATION (FIXED) ---
[pagination] # Use the capitalized key to resolve the conflict
 pagerSize = 10
 disableAliases = false
 path = 'page'

[menus]
  [[menus.main]]
    name = 'ğŸ’'
    pageRef = '/gemstones'
    weight = 10
  [[menus.main]]
    name = 'ğŸ”¬'
    pageRef = '/technique/stonesetting'
    weight = 20
  [[menus.main]]
    name = 'ğŸ§°'
    pageRef = '/toolbox'
    weight = 30
  [[menus.main]]
    name = 'ğŸ’'
    pageRef = '/categories/rings'
    weight = 50
  [[menus.footer]]
    name = 'ğŸª‘'
    pageRef = '/categories/chair'
    weight = 10
  [[menus.footer]]
    name = 'ğŸª†'
    pageRef = '/categories/dolls'
    weight = 20
  [[menus.footer]]
    name = 'ğŸª…'
    pageRef = '/categories/piÃ±ata'
    weight = 20
  [[menus.footer]]
    name = 'ğŸ‘‘'
    pageRef = '/categories/crown'
    weight = 20
  [[menus.footer]]
    name = 'ğŸ“šğŸª–ğŸ‘½ğŸ’€'
    pageRef = '/about'
    weight = 50
  [[menus.footer]]
    name = 'â›“ï¸'
    pageRef = '/categories/chains'
    weight = 50
  [[menus.categories]]
    name = 'ğŸ‘“'
    pageRef = '/categories/glasses'
    weight = 50
  [[menus.categories]]
    name = 'ğŸ§'
    pageRef = '/techniques/gemology'
    weight = 50


[taxonomies]
  tag = "tags"
  category = "categories"
  technique = "techniques"
  material = "materials"
  year = "year"
  month = "month"

[permalinks]
  notes = "notes/:year/:month/:slug/"
  year = "notes/:year/" 
  month = "notes/:year/:month/"

[related]
  threshold = 80.0
  includeNewer = false

  [[related.indices]]
    name = "materials"
    weight = 150.0

  [[related.indices]]
    name = "techniques"
    weight = 100.0

  [[related.indices]]
    name = "date"
    weight = 10.0