baseURL = 'https://www.vange.jewelry/'
languageCode = 'en-us'
title = 'vangeJewelry'

theme = 'Au'

# --- PAGINATION (FIXED) ---
[pagination] # Use the capitalized key to resolve the conflict
 pagerSize = 10
 disableAliases = false
 path = 'page'

[menus]
  [[menus.main]]
    name = 'ğŸ’€'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'ğŸ’'
    pageRef = '/creations'
    weight = 10
  [[menus.main]]
    name = 'ğŸ‘‘'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = 'ğŸ’'
    pageRef = '/knowledge'
    weight = 50
  [[menus.footer]]
    name = 'Gemstones'
    pageRef = '/gemstones'
    weight = 10
  [[menus.footer]]
    name = 'Materials'
    pageRef = '/materials'
    weight = 30
  [[menus.footer]]
    name = 'Collections'
    pageRef = '/collections'
    weight = 50
  [[menus.footer]]
    name = 'ğŸ§°'
    pageRef = '/techniques'
    weight = 70

[taxonomies]
  tag = "tags"
  category = "categories"
  technique = "techniques"
  material = "materials"
  gemstone = "gemstones"
  collection = "collections"
  year = "year"
  month = "month"

[permalinks]
  notes = "notes/:year/:month/:slug/"
  year = "notes/:year/" 
  month = "notes/:year/:month/"

[related]
  threshold = 80.0
  includeNewer = false

  [[related.indices]]
    name = "materials"
    weight = 150.0

  [[related.indices]]
    name = "techniques"
    weight = 100.0

  [[related.indices]]
    name = "date"
    weight = 10.0